# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsChat' do
  use_frameworks!

pod 'Firebase/Core', '~> 8.0.0'
pod 'Firebase/Auth'
pod 'Firebase/Database'



end
